{{- if .Values.monitor.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "smartops.fullname" . }}-monitor
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "smartops.labels" . | nindent 4 }}
    app: smartops-monitor
spec:
  schedule: {{ .Values.monitor.cronjob.schedule }}
  concurrencyPolicy: {{ .Values.monitor.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.monitor.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.monitor.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: smartops-monitor
            {{- include "smartops.selectorLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ .Values.monitor.serviceAccount.name }}
          {{- if .Values.podSecurityContext }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- end }}
          containers:
          - name: monitor
            image: {{ .Values.monitor.image.repository }}:{{ .Values.monitor.image.tag }}
            imagePullPolicy: {{ .Values.monitor.image.pullPolicy }}
            {{- if .Values.containerSecurityContext }}
            securityContext:
              {{- toYaml .Values.containerSecurityContext | nindent 14 }}
            {{- end }}
            {{- if .Values.monitor.resources }}
            resources:
              {{- toYaml .Values.monitor.resources | nindent 14 }}
            {{- end }}
          restartPolicy: OnFailure
{{- end }}
