apiVersion: v1
kind: Service
metadata:
  name: {{ include "smartops.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    app: {{ include "smartops.name" . }} 