apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-app
  namespace: smartops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartops-app
  template:
    metadata:
      labels:
        app: smartops-app
    spec:
      containers:
      - name: smartops-app
        image: sachinfe/smartops-app:latest  
        ports:
        - containerPort: 80
