apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartops-app
  template:
    metadata:
      labels:
        app: smartops-app
      annotations:
        grafana.com/metrics: "true"
        grafana.com/logs: "true"
    spec:
      containers:
        - name: smartops-app
          image: gcr.io/icbt-465109/smartops-app:latest
          ports:
            - containerPort: 80
