apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartops-app
  template:
    metadata:
      labels:
        app: smartops-app
    spec:
      containers:
      - name: smartops-app
        image: sachinfe/smartops-app:main-2025-05-22-03-44-10
        ports:
        - containerPort: 80
