apiVersion: v1
kind: Service
metadata:
  name: smartops-service
  namespace: smartops
spec:
  type: NodePort
  selector:
    app: smartops-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001 