apiVersion: v1
kind: Service
metadata:
  name: smartops-service
  namespace: smartops
spec:
  selector:
    app: smartops-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # or whatever port your app listens on
