apiVersion: v1
kind: Service
metadata:
  name: smartops-service
spec:
  type: NodePort
  selector:
    app: smartops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
