apiVersion: v1
kind: ServiceAccount
metadata:
  name: anomaly-metrics-reader
  namespace: smartops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: anomaly-metrics-reader-role
  namespace: smartops
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anomaly-metrics-reader-binding
  namespace: smartops
subjects:
- kind: ServiceAccount
  name: anomaly-metrics-reader
  namespace: smartops
roleRef:
  kind: Role
  name: anomaly-metrics-reader-role
  apiGroup: rbac.authorization.k8s.io 