apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-monitor
  namespace: smartops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartops-monitor
  template:
    metadata:
      labels:
        app: smartops-monitor
    spec:
      containers:
      - name: monitor
        image: gcr.io/icbt-465109/smartops-anomaly:latest
        command: ["python", "-u", "app/monitor_pod_status.py"] 