apiVersion: batch/v1
kind: CronJob
metadata:
  name: smartops-monitor
  namespace: smartops
spec:
  schedule: "* * * * *"  # every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: monitor
            image: us-docker.pkg.dev/icbt-465109/smartops-repo/smartops-monitor:latest
            command: ["python", "monitor_pod_status.py"]
          restartPolicy: OnFailure 