apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-anomaly-deployment
  namespace: smartops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartops-anomaly
  template:
    metadata:
      labels:
        app: smartops-anomaly
    spec:
      serviceAccountName: anomaly-metrics-reader  # ✅ Enable metrics access
      containers:
        - name: smartops-anomaly
          image: gcr.io/icbt-465109/smartops-anomaly:latest  # ⬅️ Replace with your image name if different
          ports:
            - containerPort: 8000
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
