name: Build SmartOps Docker Images

on:
  push:
    branches:
      - main
      - gcp
      - gcp2
      - alerting-logic
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAMESPACE: smartops

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin"

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Generate Image Tags
        id: tags
        run: |
          SHORT_SHA=${GITHUB_SHA::8}
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "app_tag=us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/smartops-repo/smartops-app:$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "anomaly_tag=us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/smartops-repo/smartops-anomaly:$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "dashboard_tag=us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/smartops-repo/smartops-dashboard:$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build & Push App Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/smartops-repo/smartops-app:latest
            ${{ steps.tags.outputs.app_tag }}

      - name: Build & Push Anomaly Image
        uses: docker/build-push-action@v5
        with:
          context: ./smartops-ai
          push: true
          tags: |
            us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/smartops-repo/smartops-anomaly:latest
            ${{ steps.tags.outputs.anomaly_tag }}

      - name: Build & Push Dashboard Image
        uses: docker/build-push-action@v5
        with:
          context: ./smartops-ai/dashboard
          file: ./smartops-ai/dashboard/Dockerfile
          push: true
          tags: |
            us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/smartops-repo/smartops-dashboard:latest
            ${{ steps.tags.outputs.dashboard_tag }}

      - name: Upload Image Tags Artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tags
          retention-days: 1
          path: |
            tags.env

        run: |
          echo "APP_TAG=${{ steps.tags.outputs.app_tag }}" > tags.env
          echo "ANOMALY_TAG=${{ steps.tags.outputs.anomaly_tag }}" >> tags.env
          echo "DASHBOARD_TAG=${{ steps.tags.outputs.dashboard_tag }}" >> tags.env
